services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb_user
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - data-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://admin111:admin111@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  minio:
   image: minio/minio:latest
   command: server --console-address ":9001" /data/
   ports:
     - "${MINIO_PORT}:${MINIO_PORT}"
     - "9001:9001"
   environment:
     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
   volumes:
     - minio-storage:/data
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3

volumes:
  data-volume:
  minio-storage: